apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
spec:
  capacity:
    storage:  {{ .Values.pv.storage }}
  volumeMode: Filesystem
  accessModes:
  -  {{ .Values.pv.accessMode }}
  persistentVolumeReclaimPolicy:  {{ .Values.pv.persistentVolumeReclaimPolicy }}
  storageClassName: {{ .Values.pv.storageClassName}}
  local:
    path: {{ .Values.pv.path }}

  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: {{ .Values.pv.nodeSelectorTerms.key}}
          operator: {{ .Values.pv.nodeSelectorTerms.operator}}
          values:
          - {{ .Values.pv.nodeSelectorTerms.values}}