apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
spec:
  volumeName: {{ .Values.pvc.volumeName }}
  storageClassName: local-storage
  accessModes:
  -  {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}